---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: livewall-apiserver
  namespace: default
  annotations:
    opflex.cisco.com/endpoint-group: '{"policy-space":"apicTenant","name":"livewall|api"}'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: livewall-apiserver
    spec:
      containers:
      - env:
        - name: dbHost
          value: "DBHOST"
        - name: dbUser
          value: "DBUSER"
        - name: dbPass
          value: "DBPASS"
        - name: dbName
          value: "livewall"
        image: 3pings/livewall-api:latest
        imagePullPolicy: Always
        name: livewall-apiserver
