---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: livewall-event
  namespace: default
  annotations:
    opflex.cisco.com/endpoint-group: '{"policy-space":"apicTenant","name":"livewall|collector"}'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: livewall-event
    spec:
      containers:
      - env:
        - name: dbHost
          value: "DBHOST"
        - name: dbUser
          value: "DBUSER"
        - name: dbPass
          value: "DBPASS"
        - name: dbName
          value: "livewall"
        - name: tktmst_apikey
          value: "jhoNr55QefAMxZknSaI4RmhtmcB6A6xz"
        image: 3pings/livewall-events:latest
        imagePullPolicy: Always
        name: livewall-event
